[UNDER TEST] Updates for reading from serial console
xen-troops/rcar_flash pull request #15
Opened 2023-05-09 11:03 UTC by rshym

- Rework handling of received chars
- Add `timeout` option for `wait_for`

2023-05-10 17:57 UTC, rshym commented
Successfully tested with the following cases:
- regular .srec-files
- small binary
- big (16MB) binary

Works as expected.

2023-05-10 18:00 UTC, rshym commented
@lorc could you please take a look?

2023-05-10 19:07 UTC, lorc requested changes

2023-05-10 19:07 UTC, lorc commented on rcar_flash.py
> +        rcv = chr(conn.read()[0])
Have you tested timeout case? According to doc, `conn.read()` will return an empty list and I suspect, that we will die there with something like "index out of bounds" error, which is not very helpful.

2023-05-10 19:07 UTC, lorc commented on rcar_flash.py
> -
Unsolicited change? I didn't enabled pylint in CI (yet), so it would be great if you check your patches manually.

2023-05-10 19:07 UTC, lorc commented on rcar_flash.py
> +        if "send" in evt:
So, you made `"send"` an optional? This should go into a separate commit with a proper description.

2023-05-14 15:42 UTC, rshym commented on rcar_flash.py
> +        rcv = chr(conn.read()[0])
Yes, I saw that message, and I agree that it's not very clear. So I reworked this block to catch `IndexError` and raise `TimeoutError` with the original exception included.
Here is the output in case of timeout:
```
[CRITICAL] Traceback (most recent call last):
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 344, in conn_wait_for
    rcv_char = chr(conn.read(1)[0])
IndexError: index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 699, in <module>
    main()
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 103, in main
    actions[args.action](config, args)
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 240, in do_flash
    flash_one_loader(conn, loaders[k], addr, flash_target)
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 281, in flash_one_loader
    conn_wait_for(conn, evt["wait_for"])
  File "/home/testrpi1/downloads/rcar_flash/./rcar_flash.py", line 346, in conn_wait_for
    raise TimeoutError("Nothing received from serial console.") from ierr
TimeoutError: Nothing received from serial console.
```

2023-05-14 15:42 UTC, rshym commented on rcar_flash.py
> -
Sorry, I missed this.
Removed.

2023-05-14 15:44 UTC, rshym commented on rcar_flash.py
> +        if "send" in evt:
After your comment, I decided to remove this change "send is optional" as unnecessary.
So only optional `timeout` is added, and `send` is still required.

2023-05-14 15:50 UTC, rshym commented on rcar_flash.py
> +    if print_progress:
This change is not conflicting, and even more, it is required for proper output of progress with changes to `conn_wait_for()` introduced in this PR. Main reason - flash_writer doesn't send `\r\n` when waits for file to be sent.
Here is the output without this `print("")` in PR:
```
Work RAM(H'50000000-H'53FFFFFF) Clear....
11_136/11_136 (100%) CR stop load)10_240/11_136 (91%)
```

And here is the output with print of empty line before progress:
```
Work RAM(H'50000000-H'53FFFFFF) Clear....
please send ! ('.' & CR stop load)
11_136/11_136 (100%)
```

2023-05-14 15:56 UTC, rshym commented
Please see below two examples of the script's output. Without this PR (as is now in `main` branch`) and with this PR applied.

Current `main` branch (without PR):
```
[INFO] Sending flash writer file AArch32_Flash_writer_SCIF_DUMMY_CERT_E6300400_ULCB.mot...
420_908/420_908 (100%)
  
Flash writer for R-Car H3/M3/M3N Series V1.12 Jun.4,2021
>
[INFO] Using serial port /dev/ttyUSB0 with baudrate 921600
[INFO] Writing bootparam (../firmware_dunfell_kf/bootparam_sa0-4x2g.srec) at 0x0 using gen3_hf

>
xls2
===== Qspi/HyperFlash writing of Gen3 Board Command =============
Load Program to Spiflash
Writes to any of SPI address.
Please select,FlashMemory. 
   1 : QspiFlash       (U5 : S25FS128S)
   2 : QspiFlash Board (CN2: S25FL512S)
   3 : HyperFlash      (SiP internal)
  Select (1-3)>
3
SW1    ON!                Setting OK? (Push Y key)
SW6[3] ON!                Setting OK? (Push Y key)
 READ ID OK.                                      
Program Top Address & Qspi/HyperFlash Save Address 
===== Please Input Program Top Address ============
  Please Input : H'
E6320000
 
===== Please Input Qspi/HyperFlash Save Address ===
  Please Input : H'
0
Work RAM(H'50000000-H'53FFFFFF) Clear....
please send ! ('.' & CR stop load)
11_136/11_136 (100%)

SPI Data Clear(H'FF) Check :H'00000000-0003FFFF,Clear OK?(y/n)
H'00000000-0003FFFF Erasing..Erase Completed 
SAVE SPI-FLASH....... complete!

======= Qspi/HyperFlash Save Information  =================
 SpiFlashMemory Stat Address : H'00000000
 SpiFlashMemory End Address  : H'00000E67
===========================================================

>
[INFO] All done!
[INFO] CPLD: Issuing command normal_mode
[INFO] CPLD: Issuing command reset
```

With this PR applied:
```
[INFO] Sending flash writer file AArch32_Flash_writer_SCIF_DUMMY_CERT_E6300400_ULCB.mot...

420_908/420_908 (100%)
  
Flash writer for R-Car H3/M3/M3N Series V1.12 Jun.4,2021
>[INFO] Using serial port /dev/ttyUSB0 with baudrate 921600
[INFO] Writing bootparam (../firmware_dunfell_kf/bootparam_sa0-4x2g.srec) at 0x0 using gen3_hf

>xls2
===== Qspi/HyperFlash writing of Gen3 Board Command =============
Load Program to Spiflash
Writes to any of SPI address.
Please select,FlashMemory. 
   1 : QspiFlash       (U5 : S25FS128S)
   2 : QspiFlash Board (CN2: S25FL512S)
   3 : HyperFlash      (SiP internal)
  Select (1-3)>3
 READ ID OK.                                      
Program Top Address & Qspi/HyperFlash Save Address 
===== Please Input Program Top Address ============
  Please Input : H'E6320000
 
===== Please Input Qspi/HyperFlash Save Address ===
  Please Input : H'0
Work RAM(H'50000000-H'53FFFFFF) Clear....
please send ! ('.' & CR stop load)
11_136/11_136 (100%)

SPI Data Clear(H'FF) Check :H'00000000-0003FFFF Erasing..Erase Completed 
SAVE SPI-FLASH....... complete!

======= Qspi/HyperFlash Save Information  =================
 SpiFlashMemory Stat Address : H'00000000
 SpiFlashMemory End Address  : H'00000E67
===========================================================

>[INFO] All done!
[INFO] CPLD: Issuing command normal_mode
[INFO] CPLD: Issuing command reset
```

2023-05-14 15:58 UTC, rshym commented
Reworked and tested again.
Corresponding info is added to README.
Ready for re-review.

2023-05-15 11:02 UTC, lorc commented on rcar_flash.py
> +        try:
This looking cumbersome and not pythonic. What about

```
data = conn.read(1)

if not data:
     raise TimeoutError(f"Timeout waiting for `{expect}` from the device")

rcv_char = chr(data[0])
```
?

2023-05-15 13:40 UTC, lorc approved these changes
Sorry for the extra round-trip. Please fix the last comment and add

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>` for both patches.

2023-05-15 14:45 UTC, rshym commented on rcar_flash.py
> +    orig_timeout = 10
Done. I have replaced `orig_timeout = 10` with `orig_timeout: int` and removed the comment, as not applicable.

2023-05-15 14:46 UTC, rshym commented
`RB` is added. The smoke test (flash all loaders with `-c -f .... all`) passed OK.
Ready to be merged.

2023-05-15 14:47 UTC, merged